# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 425)
        MainWindow.setMinimumSize(QtCore.QSize(0, 425))
        MainWindow.setMaximumSize(QtCore.QSize(605, 427))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxContactList = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxContactList.setGeometry(QtCore.QRect(0, 30, 191, 371))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.groupBoxContactList.setFont(font)
        self.groupBoxContactList.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxContactList.setFlat(False)
        self.groupBoxContactList.setCheckable(False)
        self.groupBoxContactList.setObjectName("groupBoxContactList")
        self.listWidgetContact = QtWidgets.QListWidget(self.groupBoxContactList)
        self.listWidgetContact.setGeometry(QtCore.QRect(10, 20, 171, 341))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setItalic(True)
        self.listWidgetContact.setFont(font)
        self.listWidgetContact.setObjectName("listWidgetContact")
        self.lineEditContactName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditContactName.setGeometry(QtCore.QRect(5, 6, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.lineEditContactName.setFont(font)
        self.lineEditContactName.setObjectName("lineEditContactName")
        self.pushButtonAddContact = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddContact.setGeometry(QtCore.QRect(140, 6, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.pushButtonAddContact.setFont(font)
        self.pushButtonAddContact.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddContact.setIcon(icon)
        self.pushButtonAddContact.setObjectName("pushButtonAddContact")
        self.pushButtonDelContact = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDelContact.setEnabled(True)
        self.pushButtonDelContact.setGeometry(QtCore.QRect(170, 6, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.pushButtonDelContact.setFont(font)
        self.pushButtonDelContact.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelContact.setIcon(icon1)
        self.pushButtonDelContact.setObjectName("pushButtonDelContact")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(191, 7, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.listWidgetChat = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetChat.setGeometry(QtCore.QRect(210, 10, 380, 331))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.listWidgetChat.setFont(font)
        self.listWidgetChat.setStyleSheet("background-color: rgb(255, 255, 240);\n"
"alternate-background-color: rgb(243, 243, 243);")
        self.listWidgetChat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidgetChat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidgetChat.setAlternatingRowColors(True)
        self.listWidgetChat.setWordWrap(True)
        self.listWidgetChat.setObjectName("listWidgetChat")
        self.plainTextEditMsg = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditMsg.setGeometry(QtCore.QRect(210, 340, 380, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.plainTextEditMsg.setFont(font)
        self.plainTextEditMsg.setObjectName("plainTextEditMsg")
        self.pushButtonSend = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSend.setGeometry(QtCore.QRect(540, 350, 41, 41))
        self.pushButtonSend.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSend.setIcon(icon2)
        self.pushButtonSend.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonSend.setFlat(True)
        self.pushButtonSend.setObjectName("pushButtonSend")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Talker"))
        self.groupBoxContactList.setTitle(_translate("MainWindow", "Список контактов"))

